[package]
name = "temporenc"
version = "0.1.0"
authors = ["Marshall Pierce <marshall@mpierce.org>"]

[dependencies]

[dev-dependencies]
rand = "0.3.15"

[profile.release]
# Uncomment when profiling with perf
#debug = true
